create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  password text not null,
  created_at timestamptz not null default now()
);

alter table public.accounts enable row level security;

-- Prototipo privado: estas políticas permiten que la app web use la clave publishable.
-- Para producción, sustituirlas por Supabase Auth y políticas por usuario.
create policy "public read accounts" on public.accounts for select to anon, authenticated using (true);
create policy "public insert accounts" on public.accounts for insert to anon, authenticated with check (true);
